# Hyprpaper Configurations 

# Disabling rendered text
splash = false

# 1440p Monitor 1 (Primary, Samsung Odyssey G6, OLED)

wallpaper {
	monitor = DP-3
	path = ~/Pictures/wallpapers/1440p Wallpapers/batmanbeyond.jpg
	fit_mode = fill
	recursive = false
}

# 1440p Monitor 2 (Secondary, LG ULTRAGEAR, IPS)

wallpaper {
	monitor = DP-4
	path = ~/Pictures/wallpapers/1440p Wallpapers/Arch.jpg
	fit_mode = fill
	recursive = false
}
